namespace MonoCloud.Authentication.Api;

/// <summary>
/// Provides options to configure the MonoCloud authentication scheme for an ASP.NET Core application.
/// </summary>
/// <remarks>
/// This type derives from <see cref="JwtBearerOptions"/>, so all of the standard JWT bearer options
/// (<see cref="JwtBearerOptions.Authority"/>, <see cref="JwtBearerOptions.TokenValidationParameters"/>,
/// <see cref="JwtBearerOptions.Audience"/>, <see cref="JwtBearerOptions.SaveToken"/>,
/// <see cref="JwtBearerOptions.MapInboundClaims"/>, <see cref="JwtBearerOptions.IncludeErrorDetails"/>, ...)
/// apply here as well and behave exactly as they do for <c>AddJwtBearer</c>. Set
/// <see cref="JwtBearerOptions.Authority"/> to the tenant domain; a value without a scheme is prefixed
/// with <c>https://</c> during post-configuration. The members declared below are the MonoCloud specific
/// additions.
/// </remarks>
public class MonoCloudAuthenticationOptions : JwtBearerOptions
{
  /// <inheritdoc />
  public MonoCloudAuthenticationOptions()
  {
    Events = new MonoCloudAuthenticationEvents();
  }

  /// <summary>
  /// Client identifier used for authentication
  /// </summary>
  public string? ClientId { get; set; }

  /// <summary>
  /// Represents the client authentication mechanism used during token validation or
  /// when making secure API calls. Checkout <see cref="ClientSecretAuth"/>, <see cref="JwtAssertionAuth"/> and <see cref="TlsAuth"/>
  /// </summary>
  public IMonoCloudClientAuth? ClientAuth { get; set; }

  /// <summary>
  /// Handler for authentication-related events during the processing of the authentication workflow.
  /// Provides extensibility points via events that can be overridden to execute custom logic at various stages,
  /// such as token validation, assertion creation, or introspection.
  /// </summary>
  public new MonoCloudAuthenticationEvents Events
  {
    get => (MonoCloudAuthenticationEvents)base.Events!;
    set => base.Events = value;
  }

  /// <summary>
  /// Indicates whether caching of token introspection results is enabled.
  /// When enabled, reduces redundant introspection network calls by reusing cached results via
  /// the registered <see cref="MonoCloud.Authentication.Api.Shared.IIntrospectionCache"/>. Only tokens validated
  /// through introspection are cached; locally validated JWTs are never cached.
  /// </summary>
  public bool EnableCaching { get; set; }

  /// <summary>
  /// Specifies the duration for which token claims are cached.
  /// This value determines the time span during which the claims are stored
  /// before they are revalidated or refreshed.
  /// </summary>
  public TimeSpan CacheDuration { get; set; } = TimeSpan.FromMinutes(5);

  /// <summary>
  /// Specifies a prefix to be applied to all cache keys generated by the caching mechanism.
  /// </summary>
  public string CacheKeyPrefix { get; set; } = string.Empty;

  /// <summary>
  /// Specifies the amount of clock skew to tolerate during token validation.
  /// When set, this value is applied to <see cref="TokenValidationParameters.ClockSkew"/> during
  /// post-configuration.
  /// </summary>
  public TimeSpan? ClockSkew { get; set; }

  /// <summary>
  /// Specifies the duration for which the generated JWT assertion is valid before expiration.
  /// This property is used to calculate the expiration (`exp`) claim for the JWT assertion.
  /// A fresh assertion is generated for every introspection request.
  /// </summary>
  public TimeSpan JwtAssertionDuration { get; set; } = TimeSpan.FromMinutes(5);

  /// <summary>
  /// Specifies the algorithm used for signing JWT assertions in client authentication flows.
  /// When not explicitly set, a default algorithm is typically applied.
  /// </summary>
  public string? JwtAssertionSigningAlgorithm { get; set; }

  /// <summary>
  /// Delegate used to determine whether certificate binding validation should be performed for the current request.
  /// </summary>
  public Func<HttpContext, bool> ValidateCertificateBinding { get; set; } = _ => false;

  /// <summary>
  /// A delegate function used to retrieve an X.509 certificate from the current HTTP context.
  /// This property allows customization of how the client certificate is accessed, providing
  /// the ability to handle scenarios where the certificate is needed for additional processing
  /// or authentication validation.
  /// </summary>
  public Func<HttpContext, Task<X509Certificate2?>> CertificateRetriever { get; set; } = async context => await context.Connection.GetClientCertificateAsync();

  /// <summary>
  /// Indicates whether JWT tokens must be introspected during authentication.
  /// When set to true, the handler validates the token using introspection,
  /// typically for scenarios where token validation is delegated to a remote authority.
  /// </summary>
  public bool IntrospectJwtTokens { get; set; }

  /// <summary>
  /// Specifies the authentication type associated with the identity,
  /// typically used for setting the claims identity's authentication method.
  /// If not explicitly set, the authentication scheme name will be used as the default value.
  /// </summary>
  public string? AuthenticationType { get; set; }

  /// <summary>
  /// Specifies the claim type to be used as the username in the identity.
  /// This value determines which claim in the token will be mapped to the user's identity name.
  /// </summary>
  public string? NameClaimType { get; set; }

  /// <summary>
  /// Specifies the claim type used to determine the roles of a user during token validation.
  /// </summary>
  public string? RoleClaimType { get; set; }

  /// <summary>
  /// A delegate used to generate a unique cache key based on the provided
  /// authentication options and token. This is primarily used in conjunction
  /// with distributed caching of token-related data.
  /// </summary>
  public Func<MonoCloudAuthenticationOptions, string, string> CacheKeyGenerator { get; set; } = Utils.CacheKeyGenerator;

  /// <summary>
  /// Provides an instance of <see cref="System.Net.Http.HttpClient"/> used to send HTTP requests
  /// and receive HTTP responses during authentication and token-related operations.
  /// This property is essential for managing HTTP communications, such as retrieving
  /// OpenID Connect configuration documents, performing token introspection,
  /// and handling certificate-based authentication in mutual TLS (mTLS) scenarios.
  /// </summary>
  /// <remarks>
  /// During post-configuration this client is also assigned to <see cref="JwtBearerOptions.Backchannel"/>,
  /// so discovery document retrieval shares it (and therefore any configured client certificate).
  /// </remarks>
  public HttpClient HttpClient { get; set; } = null!;

  /// <summary>
  /// The authentication scheme name this options instance was configured for. Assigned during
  /// post-configuration and used to namespace cache entries so distinct schemes never share cached
  /// claims for the same token.
  /// </summary>
  internal string? SchemeName { get; set; }
}
